{{ if eq .Values.deployCron false }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Values.jobName }}"
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 86400
  template:
    spec:
      containers:
        - name: "{{ .Values.jobName }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          env:
            - name: CHROME_DRIVER_LOCATION
              value: /usr/bin/chromedriver
              # Should use Workload Identity
              # Deprecated, See CRONJOB
              # kubectl create secret generic gcs-key --from-file=gcs-key.json=/Users/david/development/repos/moneycol-gcs.json
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/gcs-key.json
            - name: CRAWLING_DONE_TOPIC_NAME 
              value: "dev.crawler.events"
            - name: DATA_URI 
              value: "colnect/14-01-2022"
          resources:
            limits:
              cpu: 1
              memory: 3Gi
            requests:
              cpu: 500m
              memory: 500Mi
          volumeMounts:
            - mountPath: /var/secrets/google
              name: google-cloud-keys
      volumes:
        - name: google-cloud-keys
          secret:
            defaultMode: 420
            secretName: gcs-key
      nodeSelector:
        cloud.google.com/gke-nodepool: "indexing-pool"

      restartPolicy: Never
{{ end }}

