apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: {{ template "name" . }}-policy-member-binding
spec:
  member: serviceAccount:{{ template "name" . }}@{{ .Values.gcpProjectId }}.iam.gserviceaccount.com
  role: roles/datastore.user # Read-write access to Firestore	
  resourceRef:
    kind: Project
    name: {{ .Values.gcpProjectId }}