apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: collections-by-host
  labels:
    app: collections-by-host
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: traefik
    # This annotation rewrites the target from / -> /graphql
    # ingress.kubernetes.io/rewrite-target: /graphql 
spec:
  rules:
  - host: collections.moneycol.ml
    http:
      paths:
      - backend:
          serviceName: "collections-nodeport"
          servicePort: http
        path: /