apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: startup-script
  labels:
    app: startup-script
spec:
  selector:
    matchLabels:
      app:  startup-script
  template:
    metadata:
      labels:
        app: startup-script
    spec:
      hostPID: true
      containers:
        - name: "startup-script"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          env:
          - name: STARTUP_SCRIPT
            value: |
              #! /bin/bash
              set -o errexit
              set -o pipefail
              set -o nounset
              cd /home/app
              ./myiac setupEnvironment --project moneycol --env dev
              ./myiac deploy --app traefik --project moneycol --env dev
              touch /tmp/foo
              echo done