apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: moneycol-server-by-host
  labels:
    app: moneycol-server
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: traefik
    # This annotation rewrites the target from / -> /graphql
    ingress.kubernetes.io/rewrite-target: /graphql 
spec:
  rules:
  - host: graphql-dev.moneycol.net
    http:
      paths:
      - backend:
          serviceName: moneycolserver
          servicePort: 80
        path: /
      - backend:
          serviceName: moneycolserver
          servicePort: 80
        path: /graphql
      - backend:
          serviceName: moneycolserver
          servicePort: 80
        path: /api
      - backend:
          serviceName: moneycolserver
          servicePort: 80
        path: /.well-known
  # tls:
  # - hosts:
  #   - graphql-dev.moneycol.net
  #   secretName: traefik-dev-tls-cert
