apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: codinglove
  - http:
      paths:
      - path: /
        backend:
          serviceName: codinglove
          servicePort: 80