apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: collections-by-host
  labels:
    app: collections-by-host
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: collections.moneycol.net
      http:
        paths:
          - backend:
              serviceName: "collections-api"
              servicePort: 8080
